
[GHEGist]
  Public = false
  access_token = ""
  auto_sync = false
  base_url = ""
  file_name = ""
  gist_id = ""
  upload_url = ""

[General]
  Backend = "gist"
  Cmd = []
  Color = true
  Column = 40
  Editor = "/usr/bin/nano"
  Format = "[$description]: $command $tags"
  SelectCmd = "fzf --ansi --layout=reverse --border --height=91% --pointer=* --cycle --prompt=Snippets:"
  SnippetDirs = []
  SnippetFile = "~/.config/pet/snippet.toml"
  SortBy = ""

[Gist]
  Public = false
  access_token = ""
  auto_sync = true
  file_name = "pet-snippet.toml"
  gist_id = "13c38a50d63fac4f3f5df404c20d6e8a"

[GitLab]
  ID = ""
  Url = ""
  Visibility = "private"
  access_token = ""
  auto_sync = false
  file_name = "pet-snippet.toml"
  skip_ssl = false
